##### A short name for the species
individuals: 
   {shortened_name}: {path_to_working_dir}/{path_reference_genome}

##### The name of the species and this should be used as the working directory for the project 
##### Must be the same as the short name from above
species: {shortened_name}

##### The path to the species reference genome (should be in format so final dir == genomes)

genome_path: {path_to_working_dir}/{path_to_genomes}

##### The path to the UCE-probes 
probe_file: {path_to_working_dir}/{UCE-Path}/uce-5k-probes.fasta

##### The size of the desired flanking regions for the UCEs

flank-size: 1000

#### Params for orientation conversion script 

params_orientation: sed -e s/"'"//g | sed -e 's/set(\[\([+]]*\)\])/forward/g' | sed -e 's/set(\[\([-]]*\)\])/reverse/g'
