##### The paths to get to the samples fastq files

samples:
    {names_of_samples}: {path_to_working_dir}/{paths_to_fastq}.fastq

##### The short "individuals" name that you gave to the reference genome that the UCEs were extracted from.

UCE_individual: {shortened_name}


##### The paths to the refernce genome
ref_genome: {path_to_working_dir}/{path_to_reference_genome}.fna

ref_genome_index: {path_to_working_dir}/{path_to_reference_genome}.fna.fai


##### Mutation rate
prior_mutation_rate: 0.001

##### Short species name

species: {shortened_name}

##### The type of samples i.e. Historical, Modern, Wild

type: {type of sample}
