chrs:
    chr1: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr1.tsv
    chr2: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr2.tsv
    chr3: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr3.tsv
    chr4: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr4.tsv
    chr5: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr5.tsv
    chr6: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr6.tsv
    chr7: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr7.tsv
    chr8: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr8.tsv
    chr9: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr9.tsv
    chr10: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr10.tsv
    chr11: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr11.tsv
    chr12: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr12.tsv
    chr13: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr13.tsv
    chr14: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr14.tsv
    chr15: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr15.tsv
    chr16: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr16.tsv
    chr17: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr17.tsv
    chr18: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr18.tsv
    chr19: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr19.tsv
    chr20: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr20.tsv
    chr21: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr21.tsv
    chr22: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr22.tsv
    chr23: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr23.tsv
    chr24: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr24.tsv
    chr25: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr25.tsv
    chr26: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr26.tsv
    chr27: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr27.tsv
    chr28: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr28.tsv
    chr30: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr30.tsv
    chr31: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr31.tsv
    chr32: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr32.tsv
    chr33: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chr33.tsv
    chrZ: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/split_CADD/chCADD_chrZ.tsv


chicken_ref: /home/sspeak/projects/joint/ss_lpa_shared/chicken_Galgal6_ref/Gallus_gallus.GRCg6a.dna_rm.toplevel.fa

species_ref: /home/sspeak/projects/joint/ss_lpa_shared/Whooping-crane/ref_genome/ncbi-genomes-2023-05-03/GCF_028858705.1_bGruAme1.mat_genomic.fna.gz

chCADD_raw: /home/sspeak/projects/joint/ss_lpa_shared/chCADD_raw/chCADD.tsv.gz

######### if chain file already exists add PATH below #####

### passenger pigeon
#chain_file: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/btp_CADD_scores/galGal6ToPfasc.over.chain.gz

### Whooping crane
chain_file: /home/sspeak/projects/joint/ss_lpa_shared/Whooping-crane/chain_file_creation/galGal6ToGruAme.over.chain.gz

bed_conversion: OFS="\t"
