individuals: 
  NIATT_ARIZONA: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/base/GCA_002029285.1_NIATT_ARIZONA_genomic.fna

genome_path: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/base/genomes

probe_file: /home/sspeak/projects/joint/ss_lpa_shared/ARBOR-probes/uce-5k-probes.fasta

config_file: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/phyluce_config.txt

out_dir: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/UCE_outputs

flank-size: 1000

params_orientation: sed -e s/"'"//g | sed -e 's/set(\[\([+]]*\)\])/forward/g' | sed -e 's/set(\[\([-]]*\)\])/reverse/g'
