samples:
    SRR1303448: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/samples/SRR1303448.fastq
    SRR1303453: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/samples/SRR1303453.fastq

UCE_individual: NIATT_ARIZONA

ref_genome: /home/sspeak/projects/joint/ss_lpa_shared/passenger_pigeon/base/GCA_002029285.1_NIATT_ARIZONA_genomic.fna

prior_mutation_rate: 0.001